runtime: custom
env: flex
service: ikido_classifier

runtime_config:
  jdk: openjdk8
  
resources:
  cpu: 2
  memory_gb: 2
  
env_variables:
  SPRING_PROFILES_ACTIVE: staging
  DD_TRACE_AGENT_HOSTNAME: 'datadog-proxy.xoominfo.com'
  DD_SERVICE_NAME: 'ikido_classifier'
  DD_LOGS_INJECTION: "true"

handlers:
- url: /.*
  script: this field is required, but ignored

network:
  name: default
  subnetwork_name: default	
  instance_tag: allow-ssh
